baseURL = "http://sanjayts.net"
# baseURL = "https://sanjayts.github.io"
title = "Ramblings"
copyright = ""
enableRobotsTXT = true
enableEmoji = true

theme = "hugo-theme-even"

disqusShortname = "https-sanjayts-net"
googleAnalytics = ""
paginate = 6

# Enable pygments code fences
# PygmentsCodeFences = true

# color-codes for highlighting derived from this style
#pygmentsStyle = "emacs"

# true use pygments-css or false will color code directly
#pygmentsUseClasses = false

# [[menu.main]]             # config your menu              # 配置目录
#   name = "Home"
#   weight = 10
#   identifier = "home"
#   url = "/"

[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"
  
[[menu.main]]
  name = "Categories"
  weight = 40
  identifier = "categories"
  url = "/categories/"

[sitemap]
  changefreq = "daily"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  description = "Thoughts On Python, Scala, Big Data and Programming In General"
  copyrightOwner = "Sanjay"
  copyrightStartYear = "2017"
  favicon = "favicon.ico"
  archive-paginate = 5
  moreMeta = true

  toc = false                                                                            # 是否开启目录
  fancybox = true           # see https://github.com/fancyapps/fancybox                 # 是否启用fancybox（图片可点击）
  bootcdn = false           # In china.                                                 # 是否使用bootcdn(针对大陆推荐使用)
  mathjax = true            # see https://www.mathjax.org/                              # 是否使用mathjax（数学公式）
  linkToMarkDown = false    # if you config contentCopyright and hugo output .md files. # 是否在链接到markdown原始文件（如果你配置了下面的许可协议并允许hugo生成markdown文件）
  contentCopyright = "<a rel=\"license\" href=\"https://en.wikipedia.org/wiki/Wikipedia:Text_of_Creative_Commons_Attribution-ShareAlike_3.0_Unported_License\" target=\"_blank\">Creative Commons Attribution-ShareAlike License</a>"

  [params.social]
    a-email = "me [at] sanjayts [dot] net"
    b-stack-overflow = "https://stackoverflow.com/users/193906/sanjay-t-sharma"
    c-twitter = "https://twitter.com/sanjay_ts"
    g-github = "https://github.com/sanjayts"


[author]
  name = "Sanjay"

defaultContentLanguage = "en"

[languages]
  # edit this block for your own language
  [languages.en]
    lang = "en"
    languageName = "English"
    weight = 1
