baseURL = "http://sanjayts.net"
title = "Oblivious Ramblings"
copyright = ""

theme = "minimo"

disqusShortname = ""
googleAnalytics = ""
Paginate = 5

preserveTaxonomyNames = true

# Enable pygments code fences
PygmentsCodeFences = true

# color-codes for highlighting derived from this style
pygmentsStyle = "monokai"

# true use pygments-css or false will color code directly
pygmentsUseClasses = false

[params]
  description = "Thoughts on Python, Scala, Big Data and Programming in general"
  dateFormat = "Mon Jan 2 2006"
  copyrightOwner = "Sanjay"
  copyrightStartYear = "2017"
  favicon = "favicon.ico"
  hideEntryNavigation = false
  customCSS = ["css/custom.css"]
  customJS = ["js/custom.js"]
  hideSocialMenu = false
  showReadTime = true

[params.seo]
  # Title Separator: - – — · • * ⋆ | ~ « » < >
  titleSeparator = "•"

[params.opengraph]
  [params.opengraph.facebook]
    admins = ""
    appid = ""

[taxonomies]
  category = "categories"
  tag = "tags"

[social]
  facebook = ""

[author]
  name = "Sanjay"

[author.social]
  codepen = "sanjayts"
  email = "me [at] sanjayts [dot] net"
  github = "sanjayts"

[permalinks]
  page = "/:slug/"

# Language Configuration
defaultContentLanguage = "en"

[languages]
  # edit this block for your own language
  [languages.en]
    lang = "en"
    languageName = "English"
    weight = 1
